Hotfix/0.5
EBIvariation/opencga pull request #4
Opened 2017-04-12 13:47 UTC by pabarcgar

- Added OSS Jfron artifactory to repositories and distribution managements tags in pom.xml
- Removed biodata build from travis script

2017-04-12 14:25 UTC, cyenyxe requested changes

2017-04-12 14:25 UTC, cyenyxe commented on pom.xml
> +    <distributionManagement>
Insert blank line before this block.

2017-04-12 14:25 UTC, cyenyxe commented on pom.xml
> +            <name>oss-jfrog-artifactory-snapshots</name>
Agreed offline to use a name based on the project, not on the Artifactory repository.

2017-04-12 14:25 UTC, cyenyxe commented on pom.xml
> +        <biodata.version>0.4.7</biodata.version>
The Travis build is complaining about not finding the artifacts in "central" but they seem fine in https://oss.jfrog.org/artifactory/libs-release/uk/ac/ebi/eva/biodata-formats/ ... :thinking:

2017-04-19 10:34 UTC, pabarcgar commented on pom.xml
> +        <biodata.version>0.4.7</biodata.version>
This is fixed

2017-04-20 14:32 UTC, cyenyxe approved these changes

2017-04-20 14:33 UTC, merged